FROM jupyter/base-notebook
RUN pip install Flask==0.12 requests line-bot-sdk \
    && pip install pandas \
    && pip install scikit-learn \
    && pip install mysql-connector-python \
    && pip install numpy \
    && pip install keras \
    && pip install tensorflow \
    && pip install Pillow \
    && pip install jieba \
    && pip install redis \
    
